#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folder
mkdir -p /config/qBittorrent

# copy default config
if [[ ! -f /config/qBittorrent/qBittorrent.conf ]]; then
    cp /defaults/qBittorrent.conf /config/qBittorrent/qBittorrent.conf
fi

# copy default watched folders config
if [[ ! -f /config/qBittorrent/watched_folders.json ]]; then
    cp /defaults/watched_folders.json /config/qBittorrent/watched_folders.json
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    # chown download directory if currently not set to abc
    if grep -qe ' /downloads ' /proc/mounts; then
        lsiown abc:abc /downloads
    fi

    # permissions
    lsiown -R abc:abc \
        /config
fi
